services:
  - type: web
    name: nfc-telegram-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python NFC_RENDER.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: INTRO_GIF
        sync: false
